python:
  - 2.7
  - 3.4
os:
  - ubuntu/trusty64
env:
  CASSANDRA_VERSION:
    - 2.2.0
    - 3.0.0-alpha1
  JDK:
    - java-7-oracle
    - java-8-oracle
  EVENT_LOOP_MANAGER:
    - libev
  CYTHON:
    - CYTHON
    - NO_CYTHON
build:
  - script: |
      export JAVA_HOME=/usr/lib/jvm/$JDK
      export PATH=$JAVA_HOME/bin:$PATH
  
      # Install dependencies
      if [[ $EVENT_LOOP_MANAGER == 'libev' ]]; then
        sudo apt-get install libev4 libev-dev
      fi
      
      if [[ $CYTHON == 'CYTHON' ]]; then
        pip install cython
        pip install numpy
      fi
      
      pip install -r test-requirements.txt
      
      # Install the driver & compile C extensions
      python setup.py build_ext --inplace
      
      echo "==========RUNNING CQLENGINE TESTS=========="
      CASSANDRA_VERSION=$CASSANDRA_VERSION nosetests -s -v --with-xunit --xunit-file=cqle_results.xml tests/integration/cqlengine/
      
      echo "==========RUNNING INTEGRATION TESTS=========="
      CASSANDRA_VERSION=$CASSANDRA_VERSION nosetests -s -v --with-xunit --xunit-file=standard_results.xml tests/integration/standard/ 
      
      echo "==========RUNNING LONG INTEGRATION TESTS=========="
      CASSANDRA_VERSION=$CASSANDRA_VERSION nosetests -s -v --with-xunit --xunit-file=long_results.xml tests/integration/long/
      
